In [167]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

ag_train_df=pd.read_csv('Ag train.csv')
ag_test_df=pd.read_csv('Ag test.csv')

In [168]:
ag_train_df

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000001                      188          1          0   
1      F00000003                      209          1          0   
2      F00000004                      257          1          0   
3      F00000005                      257          1          1   
4      F00000006                      342          1          0   
...          ...                      ...        ...        ...   
88853  F00155935                     3337          1          0   
88854  F00155938                     3516          1          0   
88855  F00155939                     3516          1          0   
88856  F00155942                     3702          1          0   
88857  F00155945                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                0.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
88853                       2                 10               12.0   
88854                       2                 10               20.0   
88855                       2                 15               40.0   
88856                       2                 10               25.0   
88857                       2                 20               37.0   

       Number_Weeks_Quit  Season  Crop_Damage  
0                      0       1            0  
1                      0       2            1  
2                      0       2            1  
3                      0       2            1  
4                      0       2            1  
...                  ...     ...          ...  
88853                 44       3            0  
88854                 38       1            0  
88855                  8       2            0  
88856                 18       3            0  
88857                  7       3            0  

[88858 rows x 10 columns]

In [169]:
ag_test_df

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                      188          1          1   
1      F00000007                      410          1          1   
2      F00000011                      626          1          0   
3      F00000013                      731          1          0   
4      F00000014                      789          0          0   
...          ...                      ...        ...        ...   
59305  F00155937                     3337          1          0   
59306  F00155940                     3516          1          0   
59307  F00155941                     3702          1          0   
59308  F00155943                     3702          1          0   
59309  F00155944                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                NaN   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
59305                       2                 20               34.0   
59306                       2                 20               32.0   
59307                       2                 10                NaN   
59308                       2                 10               28.0   
59309                       2                  5               52.0   

       Number_Weeks_Quit  Season  
0                      0       2  
1                      0       2  
2                      0       2  
3                      0       2  
4                      0       1  
...                  ...     ...  
59305                 12       1  
59306                 10       2  
59307                 48       1  
59308                 17       2  
59309                  7       1  

[59310 rows x 9 columns]

In [170]:
ag_train_df.shape

(88858, 10)

In [171]:
ag_test_df.shape

(59310, 9)

In [172]:
ag_train_df.dtypes

ID                          object
Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
Crop_Damage                  int64
dtype: object

In [173]:
ag_test_df.dtypes

ID                          object
Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
dtype: object

In [174]:
for i in ag_train_df.columns: 
    x = len(ag_train_df[i].value_counts()) 
    print(x,i)

88858 ID
71 Estimated_Insects_Count
2 Crop_Type
2 Soil_Type
3 Pesticide_Use_Category
20 Number_Doses_Week
64 Number_Weeks_Used
51 Number_Weeks_Quit
3 Season
3 Crop_Damage


In [175]:
for j in ag_test_df.columns: 
    x = len(ag_test_df[j].value_counts()) 
    print(x,j)

59310 ID
71 Estimated_Insects_Count
2 Crop_Type
2 Soil_Type
3 Pesticide_Use_Category
20 Number_Doses_Week
64 Number_Weeks_Used
51 Number_Weeks_Quit
3 Season


In [176]:
ag_train_df.drop(columns='ID', inplace=True)

In [177]:
ag_train_df

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
88853                     3337          1          0                       2   
88854                     3516          1          0                       2   
88855                     3516          1          0                       2   
88856                     3702          1          0                       2   
88857                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                      0                0.0                  0       1   
1                      0                0.0                  0       2   
2                      0                0.0                  0       2   
3                      0                0.0                  0       2   
4                      0                0.0                  0       2   
...                  ...                ...                ...     ...   
88853                 10               12.0                 44       3   
88854                 10               20.0                 38       1   
88855                 15               40.0                  8       2   
88856                 10               25.0                 18       3   
88857                 20               37.0                  7       3   

       Crop_Damage  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
88853            0  
88854            0  
88855            0  
88856            0  
88857            0  

[88858 rows x 9 columns]

In [178]:
ag_test_df.drop(columns='ID', inplace=True)

In [179]:
ag_test_df

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          1                       1   
1                          410          1          1                       1   
2                          626          1          0                       1   
3                          731          1          0                       1   
4                          789          0          0                       1   
...                        ...        ...        ...                     ...   
59305                     3337          1          0                       2   
59306                     3516          1          0                       2   
59307                     3702          1          0                       2   
59308                     3702          1          0                       2   
59309                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                      0                NaN                  0       2  
1                      0                0.0                  0       2  
2                      0                0.0                  0       2  
3                      0                0.0                  0       2  
4                      0                0.0                  0       1  
...                  ...                ...                ...     ...  
59305                 20               34.0                 12       1  
59306                 20               32.0                 10       2  
59307                 10                NaN                 48       1  
59308                 10               28.0                 17       2  
59309                  5               52.0                  7       1  

[59310 rows x 8 columns]

In [180]:
y=ag_train_df['Crop_Damage']

In [181]:
y

0        0
1        1
2        1
3        1
4        1
        ..
88853    0
88854    0
88855    0
88856    0
88857    0
Name: Crop_Damage, Length: 88858, dtype: int64

In [182]:
ag_train_df.drop(columns='Crop_Damage', inplace=True)

In [183]:
ag_train_df

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
88853                     3337          1          0                       2   
88854                     3516          1          0                       2   
88855                     3516          1          0                       2   
88856                     3702          1          0                       2   
88857                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                      0                0.0                  0       1  
1                      0                0.0                  0       2  
2                      0                0.0                  0       2  
3                      0                0.0                  0       2  
4                      0                0.0                  0       2  
...                  ...                ...                ...     ...  
88853                 10               12.0                 44       3  
88854                 10               20.0                 38       1  
88855                 15               40.0                  8       2  
88856                 10               25.0                 18       3  
88857                 20               37.0                  7       3  

[88858 rows x 8 columns]

In [184]:
ag_train_df.isnull().sum()

Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          9000
Number_Weeks_Quit             0
Season                        0
dtype: int64

In [185]:
ag_test_df.isnull().sum()

Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          5893
Number_Weeks_Quit             0
Season                        0
dtype: int64

In [186]:
missing_value_percentage_train_df=pd.DataFrame({'Column_Name':ag_train_df.columns,
                                          'Missing_value_count':ag_train_df.isnull().sum(),
                                          'Missing_value_percentage':ag_train_df.isnull().sum()/ag_train_df.shape[0]*100})


missing_value_percentage_train_df=missing_value_percentage_train_df.sort_values(by='Missing_value_percentage',ascending=False)

In [187]:
missing_value_percentage_train_df

Column_Name  Missing_value_count  \
Number_Weeks_Used              Number_Weeks_Used                 9000   
Estimated_Insects_Count  Estimated_Insects_Count                    0   
Crop_Type                              Crop_Type                    0   
Soil_Type                              Soil_Type                    0   
Pesticide_Use_Category    Pesticide_Use_Category                    0   
Number_Doses_Week              Number_Doses_Week                    0   
Number_Weeks_Quit              Number_Weeks_Quit                    0   
Season                                    Season                    0   

                         Missing_value_percentage  
Number_Weeks_Used                        10.12852  
Estimated_Insects_Count                   0.00000  
Crop_Type                                 0.00000  
Soil_Type                                 0.00000  
Pesticide_Use_Category                    0.00000  
Number_Doses_Week                         0.00000  
Number_Weeks_Quit                         0.00000  
Season                                    0.00000

In [188]:
missing_value_percentage_test_df=pd.DataFrame({'Column_Name':ag_test_df.columns,
                                          'Missing_value_count':ag_test_df.isnull().sum(),
                                          'Missing_value_percentage':ag_test_df.isnull().sum()/ag_test_df.shape[0]*100})


missing_value_percentage_test_df=missing_value_percentage_test_df.sort_values(by='Missing_value_percentage',ascending=False)

In [189]:
missing_value_percentage_test_df

Column_Name  Missing_value_count  \
Number_Weeks_Used              Number_Weeks_Used                 5893   
Estimated_Insects_Count  Estimated_Insects_Count                    0   
Crop_Type                              Crop_Type                    0   
Soil_Type                              Soil_Type                    0   
Pesticide_Use_Category    Pesticide_Use_Category                    0   
Number_Doses_Week              Number_Doses_Week                    0   
Number_Weeks_Quit              Number_Weeks_Quit                    0   
Season                                    Season                    0   

                         Missing_value_percentage  
Number_Weeks_Used                         9.93593  
Estimated_Insects_Count                   0.00000  
Crop_Type                                 0.00000  
Soil_Type                                 0.00000  
Pesticide_Use_Category                    0.00000  
Number_Doses_Week                         0.00000  
Number_Weeks_Quit                         0.00000  
Season                                    0.00000

In [190]:
59310/88858

0.6674694456323572

In [191]:
from sklearn.model_selection import train_test_split

In [192]:
X_train,X_test,y_train,y_test=train_test_split(ag_train_df,y,test_size=0.2,random_state=42)

In [193]:
num_cols=[col for col in X_train.columns if X_train[col].dtype=='int64'or 
                                            X_train[col].dtype=='float64']
cat_cols=[col for col in X_train.columns if X_train[col].dtype=='object']

In [194]:
ag_train_df["Number_Weeks_Used"]=ag_train_df["Number_Weeks_Used"].fillna(ag_train_df["Number_Weeks_Used"].mean())
ag_test_df["Number_Weeks_Used"]=ag_test_df["Number_Weeks_Used"].fillna(ag_train_df["Number_Weeks_Used"].mean())

In [195]:
ag_train_df.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [196]:
ag_test_df.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [197]:
X_train.shape,X_test.shape

((71086, 8), (17772, 8))

In [198]:
for col in X_train.columns:
    if col!='Estimated_Insects_Count':
        X_train[col]=X_train[col].astype(object)
for col in X_test.columns:
    if col!='Estimated_Insects_Count':
        X_test[col]=X_test[col].astype(object)

In [199]:
cat_col=[col for col in X_train.columns if X_train[col].dtype=='object']

In [200]:
X_train_oe=pd.get_dummies(X_train[cat_col])
X_test_oe=pd.get_dummies(X_test[cat_col])
X_train_final,X_test_final=X_train_oe.align(X_test_oe,join='inner',axis=1,fill_value=0)

In [201]:
X_train_final['Estimated_Insects_Count']=X_train['Estimated_Insects_Count']
X_test_final['Estimated_Insects_Count']=X_test['Estimated_Insects_Count']

In [202]:
from sklearn.linear_model import LogisticRegression

logreg=LogisticRegression()
logreg.fit(X_train_final,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [203]:
logreg_pred=logreg.predict(X_test_final)

In [204]:
logreg_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [205]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score
confusion_matrix(y_test,logreg_pred)

array([[14589,   214,     0],
       [ 2212,   287,     0],
       [  388,    82,     0]], dtype=int64)

In [206]:
print('precision' ,precision_score(y_test,logreg_pred, average='macro'))
print('recall_score',recall_score(y_test,logreg_pred, average='macro'))
print('f1_score',f1_score(y_test,logreg_pred, average='macro'))

precision 0.4470072590535765
recall_score 0.36679646976446906
f1_score 0.3660944032244271


In [207]:
print('precision' ,precision_score(y_test,logreg_pred, average='micro'))
print('recall_score',recall_score(y_test,logreg_pred, average='micro'))
print('f1_score',f1_score(y_test,logreg_pred, average='micro'))

precision 0.8370470402880936
recall_score 0.8370470402880936
f1_score 0.8370470402880936


In [208]:
print('precision' ,precision_score(y_test,logreg_pred, average='weighted'))
print('recall_score',recall_score(y_test,logreg_pred, average='weighted'))
print('f1_score',f1_score(y_test,logreg_pred, average='weighted'))

precision 0.7761712923582351
recall_score 0.8370470402880936
f1_score 0.7858629404446704


In [209]:
from sklearn.tree import DecisionTreeClassifier

dtc=DecisionTreeClassifier(criterion="entropy",splitter="best",random_state=10)

dtc.fit(X_train_final,y_train)

dtc_pred=dtc.predict(X_test_final)

dtc_pred

array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [210]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score

confusion_matrix(y_test,dtc_pred)

array([[12694,  1817,   292],
       [ 1737,   619,   143],
       [  272,   151,    47]], dtype=int64)

In [211]:
print('Precision-Score',precision_score(y_test,dtc_pred, average='macro'))
print('Recall Score',recall_score(y_test,dtc_pred, average='macro'))
print('F1-Score',f1_score(y_test,dtc_pred, average='macro'))

Precision-Score 0.40004829392247127
Recall Score 0.40174265297102657
F1-Score 0.400862650971816


In [212]:
print('Precision-Score',precision_score(y_test,dtc_pred, average='micro'))
print('Recall Score',recall_score(y_test,dtc_pred, average='micro'))
print('F1-Score',f1_score(y_test,dtc_pred, average='micro'))

Precision-Score 0.7517443169029935
Recall Score 0.7517443169029935
F1-Score 0.7517443169029935


In [213]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=200, max_depth=6, random_state=42,oob_score=True)
rf.fit(X_train_final,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=42, verbose=0,
                       warm_start=False)

In [214]:
rf=RandomForestClassifier(oob_score=True)

In [215]:
rf.fit(X_train_final,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [216]:
rf_pred=rf.predict(X_test_final)

In [218]:
rf_pred

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [220]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score

confusion_matrix(y_test,rf_pred)

array([[13904,   780,   119],
       [ 1896,   485,   118],
       [  285,   141,    44]], dtype=int64)

In [223]:
print('Precision-Score',precision_score(y_test,rf_pred, average='macro'))
print('Recall Score',recall_score(y_test,rf_pred, average='macro'))
print('F1-Score',f1_score(y_test,rf_pred, average='macro'))

Precision-Score 0.45531389221654867
Recall Score 0.4089879064700046
F1-Score 0.42195382844157886


In [224]:
print('Precision-Score',precision_score(y_test,rf_pred, average='micro'))
print('Recall Score',recall_score(y_test,rf_pred, average='micro'))
print('F1-Score',f1_score(y_test,rf_pred, average='micro'))

Precision-Score 0.812120189061445
Recall Score 0.812120189061445
F1-Score 0.812120189061445


In [228]:
print('Precision-Score',precision_score(y_test,rf_pred, average='weighted'))
print('Recall Score',recall_score(y_test,rf_pred, average='weighted'))
print('F1-Score',f1_score(y_test,rf_pred, average='weighted'))

Precision-Score 0.7726453998911132
Recall Score 0.812120189061445
F1-Score 0.7879102484079207
